title: ClubHub
description: The hub for all of UH Manoa's Clubs 
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme

gems:
  - jekyll-mentions
